% Display table with results for synthetic data sets 

%LaTeX Tables    
fprintf('\\begin{center}  \n \\begin{table}[h!] \n \\begin{center} \n');
fprintf('\\caption{Average relative error (in \\%%) and runtime, as well as their standard deviations\n');  
fprintf('for CVX, FGM, AN-FGM on 20 randomly generated problems for 9 different scenarios. \\label{tab:results} } \n'); 
fprintf(' \\begin{tabular}{|c|c|c||c|c|c|} \n \\hline');
fprintf('          &          &             &         SDPT3         &        FGM       &       AN-FGM      \\\\ \\hline \n')

fprintf(' Well-conditioned& $m=n=%2.0f$ & rel. err.   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(1,1,:)), std( ecvxm(1,1,:)), mean( efgmm(1,1,:)), std( efgmm(1,1,:)),mean( eanfgmm(1,1,:)), std( eanfgmm(1,1,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f   &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \n', ...
    mean( tcvxm(1,1,:)), std( tcvxm(1,1,:)), mean( tfgmm(1,1,:)), std( tfgmm(1,1,:)),mean( tanfgmm(1,1,:)), std( tanfgmm(1,1,:))   );
  
fprintf('                 & $m=2n=%2.0f$& rel. err.   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(1,2,:)), std( ecvxm(1,2,:)), mean( efgmm(1,2,:)), std( efgmm(1,2,:)),mean( eanfgmm(1,2,:)), std( eanfgmm(1,2,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f     &  %1.2f $\\pm$ %1.2f   &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \n', ...
    mean( tcvxm(1,2,:)), std( tcvxm(1,2,:)), mean( tfgmm(1,2,:)), std( tfgmm(1,2,:)),mean( tanfgmm(1,2,:)), std( tanfgmm(1,2,:))   );

fprintf('                 & $n=2m=%2.0f$ & rel. err.  &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(1,3,:)), std( ecvxm(1,3,:)), mean( efgmm(1,3,:)), std( efgmm(1,3,:)),mean( eanfgmm(1,3,:)), std( eanfgmm(1,3,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f   &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \\hline \n', ...
    mean( tcvxm(1,3,:)), std( tcvxm(1,3,:)), mean( tfgmm(1,3,:)), std( tfgmm(1,3,:)),mean( tanfgmm(1,3,:)), std( tanfgmm(1,3,:))   );

fprintf(' Ill-conditioned & $m=n=%2.0f$ & rel. err.   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(2,1,:)), std( ecvxm(2,1,:)), mean( efgmm(2,1,:)), std( efgmm(2,1,:)),mean( eanfgmm(2,1,:)), std( eanfgmm(2,1,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \n', ...
    mean( tcvxm(2,1,:)), std( tcvxm(2,1,:)), mean( tfgmm(2,1,:)), std( tfgmm(2,1,:)),mean( tanfgmm(2,1,:)), std( tanfgmm(2,1,:))   );
  
fprintf('                 & $m=2n=%2.0f$& rel. err.   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(2,2,:)), std( ecvxm(2,2,:)), mean( efgmm(2,2,:)), std( efgmm(2,2,:)),mean( eanfgmm(2,2,:)), std( eanfgmm(2,2,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f     &  %1.2f $\\pm$ %1.2f   &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \n', ...
    mean( tcvxm(2,2,:)), std( tcvxm(2,2,:)), mean( tfgmm(2,2,:)), std( tfgmm(2,2,:)),mean( tanfgmm(2,2,:)), std( tanfgmm(2,2,:))   );

fprintf('                 & $n=2m=%2.0f$& rel. err.   &   %1.2f $\\pm$ %1.2f   &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(2,3,:)), std( ecvxm(2,3,:)), mean( efgmm(2,3,:)), std( efgmm(2,3,:)),mean( eanfgmm(2,3,:)), std( eanfgmm(2,3,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \\hline \n', ...
    mean( tcvxm(2,3,:)), std( tcvxm(2,3,:)), mean( tfgmm(2,3,:)), std( tfgmm(2,3,:)),mean( tanfgmm(2,3,:)), std( tanfgmm(2,3,:))   );


fprintf(' Rank-deficient  & $m=n=%2.0f$ & rel. err.   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(3,1,:)), std( ecvxm(3,1,:)), mean( efgmm(3,1,:)), std( efgmm(3,1,:)),mean( eanfgmm(3,1,:)), std( eanfgmm(3,1,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f   &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \n', ...
    mean( tcvxm(3,1,:)), std( tcvxm(3,1,:)), mean( tfgmm(3,1,:)), std( tfgmm(3,1,:)),mean( tanfgmm(3,1,:)), std( tanfgmm(3,1,:))   );
  
fprintf('                 & $m=2n=%2.0f$& rel. err.   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(3,2,:)), std( ecvxm(3,2,:)), mean( efgmm(3,2,:)), std( efgmm(3,2,:)),mean( eanfgmm(3,2,:)), std( eanfgmm(3,2,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f     &  %1.2f $\\pm$ %1.2f   &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \n', ...
    mean( tcvxm(3,2,:)), std( tcvxm(3,2,:)), mean( tfgmm(3,2,:)), std( tfgmm(3,2,:)),mean( tanfgmm(3,2,:)), std( tanfgmm(3,2,:))   );

fprintf('                 & $n=2m=%2.0f$ & rel. err.  &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f  &   %1.2f  $\\pm$ %1.2f  \\\\ \n', ...
    max(m,n), mean( ecvxm(3,3,:)), std( ecvxm(3,3,:)), mean( efgmm(3,3,:)), std( efgmm(3,3,:)),mean( eanfgmm(3,3,:)), std( eanfgmm(3,3,:))   );
fprintf('                 &          & time (s.)   &   %1.2f $\\pm$ %1.2f    &  %1.2f $\\pm$ %1.2f   &   %1.2f  $\\pm$ %1.2f  \\\\ \\hline \n', ...
    mean( tcvxm(3,3,:)), std( tcvxm(3,3,:)), mean( tfgmm(3,3,:)), std( tfgmm(3,3,:)),mean( tanfgmm(3,3,:)), std( tanfgmm(3,3,:))   );


fprintf('\\end{tabular} \n \\end{center} \n \\end{table} \n \\end{center} \n');